CC = gcc
CFLAGS = -m32 -ffreestanding -O2 -Wall -Wextra -Ikernel
ASM = nasm
ASMFLAGS = -f elf32

C_SOURCES = $(wildcard kernel/*.c)
ASM_SOURCES = $(wildcard boot/*.asm kernel/*.asm)

OBJ = $(C_SOURCES:.c=.o) $(ASM_SOURCES:.asm=.o)

all: os-image.bin

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.asm
	$(ASM) $(ASMFLAGS) $< -o $@

os-image.bin: $(OBJ) linker.ld
	ld -m elf_i386 -T linker.ld -o os-image.bin $(OBJ)

clean:
	rm -f kernel/*.o boot/*.o *.bin